### ISSUE TITLE
Larger uploads fail - error handling not possible (status undefined)

### ISSUE THREAD

**Issue by unbekanntes-pferd** [GDATASoftwareAG/vaas#81] opened 2022-08-31 20:31 UTC
Uploading a larger file (>10MB) leads to an error - root cause unknown, but error shows the following: 

```
/usr/src/app/node_modules/gdata-vaas/lib/vaas.js:191
                    reject(new Error(`Upload failed with ${error.response.status} - Error ${error.response.data.message}`));
                                                                          ^

TypeError: Cannot read properties of undefined (reading 'status')
    at /usr/src/app/node_modules/gdata-vaas/lib/vaas.js:191:75
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.8.0
```

I can reliably reproduce this issue for files larger than 10 MB (smaller files work fine).
The error cannot be caught in a try/catch block due to 'status' being undefined.
Please let me know if you need more info.

Code snippet attached (as screenshot) - error appears using the forFile method.

![image](https://user-images.githubusercontent.com/70800577/187776109-ec7a641d-f77a-473f-a5ff-37454bc2373f.png)

**Comment by doxthree** [comment] 2022-09-01 11:51
Hey @unbekanntes-pferd,

thank you for your bug report. We will investigate why the problem is occurring and get back to you as soon as we find the cause for this issue.

**Comment by pstadermann** [comment] 2022-09-01 17:55
Please try again with the latest version 2.2.1. The issue should be fixed.

**Closed** 2022-09-01 17:55 UTC
Labels: bug

**Comment by pstadermann** [comment] 2022-09-02 05:57
We had some issues with the Github actions. The latest version is 2.2.3, which has the same code as 2.2.1, but was deployed from Github.
